services:
  database:
    image: 'postgres:latest'
    ports:
    - '5432:5432'
    environment:
      - 'POSTGRES_USER=learnSpring'
      - 'POSTGRES_DB=learnSpring'
      - 'POSTGRES_PASSWORD=learnSpring'
    volumes:
      - './volumes/learnSpring/postgres:/var/lib/postgresql/data'